<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AVLSet.fs"/>
    <Compile Include="Utils.fs"/>
    <Compile Include="BFS.fs"/>
    <Compile Include="SSSP.fs"/>
    <Compile Include="Triangles.fs"/>
    <Compile Include="ReduceComparison.fs"/>
    <Compile Include="VectorSlice.fs"/>
    <Compile Include="MatrixSlice.fs"/>
    <Compile Include="Kronecker.fs"/>
    <Compile Include="MatrixSliceAlign.fs"/>
    <Compile Include="VectorSliceAlign.fs"/>
    <Compile Include="FormatBenchmarks.fs"/>
    <Compile Include="RealMatrixBenchmark.fs"/>
    <Compile Include="Main.fs"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuadTree\QuadTree.fsproj" />
  </ItemGroup>

</Project>

